Fix bug in CSV writer
palvarezc/cavendish-particle-tracks pull request #189
Opened 2024-10-14 21:24 UTC by palvarezc

Removed unwanted commas that messed up the CVS file.

2024-10-14 22:14 UTC, samcunliffe approved these changes

2024-10-14 22:14 UTC, samcunliffe commented on src/cavendish_particle_tracks/analysis.py
> +        mystring += f"sp2=[{self._sp2[0]} {self._sp2[1]}]; "
```suggestion
        for name, point in zip(["sf1", "sf2", "sp1", "sp2"], [self._sf1, self._sf2, self._sp1, self._sp2]):
            x, y = point
            mystring += f"{name}=[{x} {y}]; "
```

2024-10-14 22:14 UTC, samcunliffe commented on src/cavendish_particle_tracks/analysis.py
> +                    mystring += "[" + str(point[0]) + " " + str(point[1]) + "]; "
```suggestion
                for point in getattr(self, var):
                    x, y = point
                    mystring += "[{x} {y}]; "
```

2024-10-14 22:14 UTC, samcunliffe commented on tests/test_save.py
> +    file_name = "my_file.csv"
```suggestion
    file_name = "test_saved_file.csv"
```

2024-10-14 22:14 UTC, samcunliffe commented on tests/test_save.py
> +    def set_filename_and_close(dialog):
```suggestion
    def set_filename_and_close(dialog):
        # Function of the signature needed to use as a dialog action.
        # Defined internally so we can access the fixtures without passing.
```

2024-10-14 22:18 UTC, samcunliffe requested changes

2024-10-14 22:18 UTC, samcunliffe commented on src/cavendish_particle_tracks/analysis.py
> +                    mystring += "[{x} {y}]; "
```suggestion
                    mystring += "f[{x} {y}]; "
```

2024-10-14 22:19 UTC, samcunliffe commented on src/cavendish_particle_tracks/analysis.py
> +                    mystring += "[{x} {y}]; "
Sorry. Would be good maybe to commit an expected CSV file into test data? Can then do regression testing.

2024-10-14 22:23 UTC, samcunliffe commented on src/cavendish_particle_tracks/analysis.py
> +                    mystring += "[{x} {y}]; "
Looks like [`filecmp`](https://docs.python.org/3/library/filecmp.html) does it. And it's a builtin.

- https://stackoverflow.com/q/75838502/1444054
   (the first comment about asserting on an empty diff looks nice).

2024-10-14 22:23 UTC, samcunliffe approved these changes

2024-10-15 08:22 UTC, samcunliffe commented
@palvarezc I leave you to merge if you're OK with my reimplemented `filecmp`.

2024-10-15 10:19 UTC, palvarezc commented
Thanks!

2024-10-15 10:19 UTC, merged